AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  RedirectUrl:
    Type: String
Description: Basic Redirector
Resources:
  RedirectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /
            Method: get
      CodeUri: .
      Environment:
        Variables:
          REDIRECT_URL: !Ref RedirectUrl
  RedirectorLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub:
        - "/aws/lambda/${LambdaName}"
        - LambdaName: !Ref RedirectorFunction
      RetentionInDays: 90