AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket for lambda/cf artifcats
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
Outputs:
  ArtifactBucketArn:
    Value: !GetAtt ArtifactBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-Arn"