AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DockerBuildRoleArn:
    Type: String
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: gemini
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
                {
                    "rulePriority": 10,
                    "description": "release docker image gc",
                    "selection": {
                        "tagStatus": "any",
                        "countType": "imageCountMoreThan",
                        "countNumber": 20
                    },
                    "action": {
                        "type": "expire"
                    }
                }
            ]
          }
      RepositoryPolicyText: !Sub |
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Sid": "builder",
              "Effect": "Allow",
              "Principal": {
                "AWS": "${DockerBuildRoleArn}"
              },
              "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:CompleteLayerUpload",
                "ecr:GetDownloadUrlForLayer",
                "ecr:InitiateLayerUpload",
                "ecr:PutImage",
                "ecr:UploadLayerPart"
              ]
            },
            {
              "Sid": "onlyforcodebuildimages",
              "Effect": "Allow",
              "Principal": {
                "Service": "codebuild.amazonaws.com"
              },
              "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:GetDownloadUrlForLayer"
              ]
            }
          ]
        }