AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ECSAMI:
    Description: AMI ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: !ImportValue HyperdriveCore-ECSInstanceProfile
      ImageId: !Ref ECSAMI
      InstanceMonitoring: false
      InstanceType: t3.micro
      SecurityGroups: !Ref SecurityGroups
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

            echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
            echo ECS_ENABLE_TASK_IAM_ROLE=true >> /etc/ecs/ecs.config
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 1
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: 1
      MinSize: 1
      VPCZoneIdentifier: !Ref Subnets
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
