AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RedirectorApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "HyperdriveRedirector"
      Body:
        swagger: "2.0"
        info:
          version: "1.0"
        schemes:
          - "https"
        paths:
          /:
            get:
              consumes:
                - "application/json"
              responses:
                "301":
                  description: "301 response"
                  headers:
                    Location:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  "301":
                    statusCode: "301"
                    responseParameters:
                      method.response.header.Location: "stageVariables.redirectLocation"
                requestTemplates:
                  application/json: "{\"statusCode\": 301}"
                passthroughBehavior: "when_no_match"
                type: "mock"
        definitions:
          Empty:
            type: "object"
            title: "Empty Schema"
  RedirectorDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Initial Deployment
      RestApiId: !Ref RedirectorApi
Outputs:
  Api:
    Value: !Ref RedirectorApi
    Export:
      Name: !Sub "${AWS::StackName}-Api"
  Deployment:
    Value: !Ref RedirectorDeployment
    Export:
      Name: !Sub "${AWS::StackName}-Deployment"
